const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const header=$('.site-header'),toggle=$('.nav-toggle'),navLinks=$('.nav-links');
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30));
toggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});
$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));

const features=[['💧','100% Pure','Carefully processed to preserve quality and freshness.'],['🌱','Premium Seeds','Selected raw materials from dependable sources.'],['⚙️','Advanced Refining','Modern systems with controlled processing standards.'],['🛡️','No Adulteration','Strong quality controls for every production batch.'],['🧪','Lab Tested','Routine testing for consistency, safety and purity.'],['📦','Food Grade Packaging','Protective packaging designed for freshness.'],['✨','Rich in Vitamins','Everyday nutrition for balanced family cooking.'],['🤝','Trusted Quality','A promise built on care, reliability and service.']];
$('#features').innerHTML=features.map(([i,t,d])=>`<article class="feature-card reveal"><div class="icon-box">${i}</div><h3>${t}</h3><p>${d}</p></article>`).join('');
const steps=[['🌾','Seed Selection'],['🫧','Cleaning'],['🌀','Extraction'],['⚙️','Refining'],['🧪','Quality Testing'],['🧴','Packaging'],['🚚','Distribution']];
$('#processLine').innerHTML=steps.map(([i,t])=>`<div class="process-step reveal"><div class="process-icon">${i}</div><h3>${t}</h3></div>`).join('');
const benefits={groundnut:{title:'Groundnut Oil',img:'assets/images/groundnut-field.svg',items:['Naturally balanced healthy fats','A source of Vitamin E','Suitable for frying and daily cooking','Rich, familiar taste for Indian kitchens']},sunflower:{title:'Sunflower Oil',img:'assets/images/sunflower-field.svg',items:['Light taste and clean finish','Popular for everyday family cooking','Naturally contains Vitamin E','Works well for sautéing and frying']},soybean:{title:'Soybean Oil',img:'assets/images/soybean-field.svg',items:['Contains essential fatty acids','Balanced option for everyday meals','Smooth and versatile flavour profile','Suitable for multiple cooking methods']},mustard:{title:'Mustard Oil',img:'assets/images/mustard-field.svg',items:['Authentic aroma for traditional cuisine','Naturally bold flavour','Well suited to pickling and regional recipes','Contains naturally occurring antioxidants']}};
function showBenefit(key){const b=benefits[key];$('#benefitPanel').innerHTML=`<img src="${b.img}" alt="${b.title} ingredients"><div><span class="eyebrow">${b.title}</span><h3 style="font-family:Playfair Display;font-size:34px;margin:0">Naturally suited to your kitchen.</h3><ul>${b.items.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;$$('.benefit-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.benefit===key))}
showBenefit('groundnut');$$('.benefit-tabs button').forEach(b=>b.addEventListener('click',()=>showBenefit(b.dataset.benefit)));
const certs=[['ISO','International Standards'],['FSSAI','Food Compliance'],['✓','Quality Tested'],['🛡️','Food Safety'],['🧪','Modern Laboratory'],['📦','Premium Packaging']];
$('#certGrid').innerHTML=certs.map(([i,t])=>`<div class="cert-card reveal"><span>${i}</span><b>${t}</b></div>`).join('');
const galleries=[['assets/images/gallery-bottles.svg','Premium Oil Bottles'],['assets/images/gallery-factory.svg','Manufacturing Facility'],['assets/images/gallery-seeds.svg','Carefully Selected Seeds'],['assets/images/gallery-sunflower.svg','Sunflower Farms'],['assets/images/gallery-lab.svg','Quality Laboratory'],['assets/images/gallery-packaging.svg','Modern Packaging'],['assets/images/gallery-warehouse.svg','Organized Warehouse'],['assets/images/gallery-mustard.svg','Mustard Fields']];
$('#galleryGrid').innerHTML=galleries.map(([src,title],i)=>`<figure class="gallery-item reveal" data-title="${title}" data-src="${src}"><img loading="lazy" src="${src}" alt="${title}" style="aspect-ratio:${i%3===0?'4/5':'4/3'};object-fit:cover"></figure>`).join('');
const lightbox=$('#lightbox');$$('.gallery-item').forEach(g=>g.addEventListener('click',()=>{lightbox.classList.add('open');$('img',lightbox).src=g.dataset.src;$('img',lightbox).alt=g.dataset.title}));$('button',lightbox).addEventListener('click',()=>lightbox.classList.remove('open'));lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.classList.remove('open')});
const testimonials=[['“JRP Oils gives us the consistency we need for high-volume cooking without compromising taste.”','Restaurant Partner','Hospitality'],['“The packaging, product quality and dependable supply make JRP Oils easy to recommend to customers.”','Retail Partner','Modern Trade'],['“A trustworthy product range with good customer response and strong distributor support.”','Authorized Dealer','Distribution'],['“Light, fresh and reliable for daily family meals. It fits naturally into our kitchen.”','Family Customer','Home Cooking']];
$('#testimonialTrack').innerHTML=testimonials.map(([q,n,r])=>`<article class="testimonial-card"><div class="stars">★★★★★</div><blockquote>${q}</blockquote><b>${n}</b><small style="display:block;color:#777">${r}</small></article>`).join('');
$('#sliderDots').innerHTML=testimonials.map((_,i)=>`<button aria-label="Show testimonial ${i+1}" class="${i===0?'active':''}"></button>`).join('');let slide=0;function goSlide(i){slide=i;$('#testimonialTrack').style.transform=`translateX(-${i*100}%)`;$$('#sliderDots button').forEach((b,j)=>b.classList.toggle('active',j===i))}$$('#sliderDots button').forEach((b,i)=>b.addEventListener('click',()=>goSlide(i)));setInterval(()=>goSlide((slide+1)%testimonials.length),5000);
const faqs=[['What is the typical shelf life?','Shelf life depends on the product and pack format. The exact best-before period is printed clearly on every package.'],['Which packaging sizes are available?','JRP Oils can support multiple consumer and bulk pack formats. Contact our sales team for the current packaging range.'],['Do you accept bulk orders?','Yes. Bulk and institutional inquiries are welcome, subject to product availability and commercial terms.'],['Is private labeling available?','Private-label opportunities can be evaluated based on volume, packaging needs and compliance requirements.'],['Are cold-pressed oils available?','The Phase 1 range focuses on core edible oil categories. Contact us to discuss planned or custom product options.'],['Do you offer wholesale or dealership opportunities?','Yes. We welcome serious distributor, wholesaler and retail partnership inquiries in selected markets.']];
$('#faqList').innerHTML=faqs.map(([q,a],i)=>`<div class="accordion-item reveal"><button class="accordion-button" aria-expanded="false">${q}<span>+</span></button><div class="accordion-content"><p>${a}</p></div></div>`).join('');$$('.accordion-button').forEach(b=>b.addEventListener('click',()=>{const item=b.parentElement;const open=item.classList.toggle('open');b.setAttribute('aria-expanded',open);$('span',b).textContent=open?'−':'+'}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
let counted=false;const statObs=new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&!counted){counted=true;$$('[data-count]').forEach(el=>{const target=+el.dataset.count,suffix=el.dataset.suffix;let start=0;const dur=1400,st=performance.now();function tick(now){const p=Math.min((now-st)/dur,1);start=Math.floor(target*(1-Math.pow(1-p,3)));el.textContent=start+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}},{threshold:.35});statObs.observe($('.stats'));
$('#inquiryForm').addEventListener('submit',e=>{e.preventDefault();$('.form-status').textContent='Thank you. Your inquiry has been captured in this demo. Connect the form to your preferred email or backend service before launch.';e.target.reset()});
$('#year').textContent=new Date().getFullYear();
